import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBare from "@/components/Bares/NavBare";
import LeftLine from "@/components/Bares/LeftLine";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abdelbari",
  description: "Portfolio Generated by Abdelbari MESSAH",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-fira-code">
      <link rel="icon" href="/assets/favicon.ico" sizes="any" />
      <body className="no-scrollbar overflow-x-hidden bg-color-1">
        <div className="flex bg-color-1 flex-col w-screen min-h-screen relative no-scrollbar">
          <div className="flex items-center justify-center w-full absolute top-0 ">
            <LeftLine />
            <NavBare />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
